# Generated by Django 3.2 on 2021-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQuality', models.CharField(max_length=30)),
                ('productDelivery', models.CharField(max_length=30)),
                ('communication', models.CharField(max_length=30)),
                ('behaviour', models.CharField(max_length=30)),
                ('paperwork', models.CharField(max_length=30)),
                ('packingInnerQuality', models.CharField(max_length=30)),
                ('packingOuterQuality', models.CharField(max_length=30)),
                ('presentationAndCatalogues', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('dealerName', models.CharField(max_length=50)),
                ('goods', models.CharField(max_length=40)),
            ],
        ),
    ]
