# Generated by Django 3.2 on 2021-07-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_comments_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='replyMailSent',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='replyMailSent',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replyMailSent',
            field=models.CharField(default='', max_length=20),
        ),
    ]
